version: "3.2"

services:
  bonuscalc-api:
    image: bonuscalc-api
    build:
      context: .
      dockerfile: BonusCalcApi/Dockerfile
    ports:
      - 3000:3000
    environment:
      - CONNECTION_STRING=Host=dev-database;Port=5432;Database=testdb;Username=postgres;Password=mypassword
    depends_on:
      - dev-database

  dev-database:
    image: postgres:12
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  bonuscalc-api-test:
    image: bonuscalc-api-test
    build:
      context: .
      dockerfile: BonusCalcApi.Tests/Dockerfile
    environment:
      - DB_HOST=test-database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=mypassword
      - DB_DATABASE=testdb
    depends_on:
      - test-database

  test-database:
    image: postgres:12
    ports:
      - 5435:5432
    env_file:
      - database.env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
