// <auto-generated />
using BonusCalcApi.V1.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace V1.Infrastructure.Migrations
{
    [DbContext(typeof(BonusCalcContext))]
    [Migration("20211007105426_CreateOperative")]
    partial class CreateOperative
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("BonusCalcApi.V1.Infrastructure.Operative", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<string>("Trade")
                        .HasColumnName("trade")
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .HasColumnName("section")
                        .HasColumnType("text");

                    b.Property<string>("Scheme")
                        .HasColumnName("scheme")
                        .HasColumnType("text");

                    b.Property<int>("SalaryBand")
                        .HasColumnName("salary_band")
                        .HasColumnType("integer");

                    b.Property<string>("FixedBand")
                        .HasColumnName("fixed_band")
                        .HasColumnType("boolean");

                    b.Property<string>("IsArchived")
                        .HasColumnName("is_archived")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("operatives");
                });
#pragma warning restore 612, 618
        }
    }
}
